---
- hosts: localhost
  name: DB Backup Volume Info Test
  gather_facts: false
  vars_files:
    - /home/CTS_NetApp_Python/Ansible/DB_Backup/var/@var.yml
  tasks:
    - name: IMG and LOG Volume Size_Count Info
      db_backup_vol_info:
        DB_SIZE: "{{ db_size }}"
        MAX_VOL_SIZE: "{{ max_vol_size }}"
      register: testout
    - name: Dump Test Output
      debug:
        msg: "{{ testout.volume_count_img }}"
