---
- hosts: localhost
  name: DB Backup Volume Create
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    login: &login
      hostname: "{{ na_hostname }}"
      username: "{{ na_username }}"
      password: "{{ na_password }}"
      https: true
      validate_certs: false
    vserver: "{{ vserver_name }}"
    aggr: "{{ aggr_name }}"
    vol_base: "{{ client_name }}_{{ db_name }}_IMG01_"
    vols: []  # Initialize an empty list for volume counts
  vars_files:
    - /home/CTS_NetApp_Python/Ansible/DB_Backup/var/@var.yml
    - /home/CTS_NetApp_Python/Ansible/DB_Backup/var/@var_volinfo.yml
  tasks:
    - name: Volume Create
      na_ontap_volume:
        state: present
        name: "{{ vol_base }}{{ '%03d' | format(item|int) }}"
        vserver: "{{ vserver }}"
        aggregate_name: "{{ aggr }}"
        size: "{{ volume_size }}"
        size_unit: gb
        policy: default
        junction_path: "/{{ vol_base }}{{ '%03d' | format(item|int) }}"
        <<: *login
      loop: "{{ range(1, volume_count + 1) | list }}"
